### ISSUE TITLE
CouchDB server doesn't start.

### ISSUE THREAD

**Issue by thomascenni** [bitnami/bitnami-docker-couchdb#1] opened 2020-06-24 00:30 UTC
**Description**

CouchDB server doesn't start.

**Steps to reproduce the issue:**

docker run --name couchdb bitnami/couchdb:latest

**Describe the results you received:**

I receive the following error:
couchdb 22:41:43.03 INFO  ==> ** Starting CouchDB setup **
couchdb 22:41:43.07 INFO  ==> Initializing CouchDB...
couchdb 22:41:43.07 INFO  ==> Updating '/opt/bitnami/couchdb/etc/default.d/10-bitnami.ini' based on user configuration...
/opt/bitnami/scripts/libcouchdb.sh: line 178: 3: value is required

**Describe the results you expected:**

I expected the server to start normally.

**Version**

- Output of `docker version`:

```
Client: Docker Engine - Community
 Version:           19.03.5
 API version:       1.40
 Go version:        go1.12.12
 Git commit:        633a0ea
 Built:             Wed Nov 13 07:22:34 2019
 OS/Arch:           darwin/amd64
 Experimental:      false
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**
Docker for Mac on macOS Sierra 10.12.6

**Comment by carrodher** [comment] 2020-06-24 07:16
Hi, thanks for reporting the issue. I am able to reproduce it and I just created an internal task to fix it in the next release.

The source of the issue is that the `COUCHDB_PASSWORD` environment variable is needed, as you can see in the [docker-compose.yaml](https://github.com/bitnami/bitnami-docker-couchdb/blob/master/docker-compose.yml#L6) we are setting it:
```yaml
  couchdb:
    image: docker.io/bitnami/couchdb:3-debian-10
    environment:
      - COUCHDB_PASSWORD=couchdb
```
that is not translated to the `docker run` execution, so we are going to set this default value in the container logic. In the meantime, you can set this environment variable:
```console
$ docker run --name couchdb -e 'COUCHDB_PASSWORD=couchdb' bitnami/couchdb:latest
```

Once released the new version with the fix, it won't be necessary to use this workaround.

**Comment by carrodher** [comment] 2020-06-24 12:09
Hi,

the new version was released in this commit fa04921ade3a69fd41bbcce1a75d579dd70dee95, now the environment variable has a default value so you can execute `docker run bitnami/couchdb` without extra arguments and it should work.

If you are using `latest` or another rolling tag like `3.1.0`, please ensure the new version is pulled:
```console
$ docker run bitnami/couchdb:latest
Unable to find image 'bitnami/couchdb:latest' locally
latest: Pulling from bitnami/couchdb
20b41457e783: Pull complete
df0a44c882d2: Pull complete
50f489f30371: Pull complete
55ac83aa9866: Pull complete
a2dd1484ab7d: Pull complete
fffd384d26bc: Pull complete
b0d84d510d54: Pull complete
5ed55421fcb2: Pull complete
6aff6b711004: Pull complete
f29ec6c473cf: Pull complete
Digest: sha256:241f39a6c15335e69783f74de555347179941f4ee64a71e3e41654f13c930ffa
Status: Downloaded newer image for bitnami/couchdb:latest
couchdb 12:07:54.61
couchdb 12:07:54.61 Welcome to the Bitnami couchdb container
couchdb 12:07:54.61 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-couchdb
couchdb 12:07:54.61 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-couchdb/issues
couchdb 12:07:54.62
couchdb 12:07:54.62 INFO  ==> ** Starting CouchDB setup **
couchdb 12:07:54.62 WARN  ==> You set the environment variable COUCHDB_PASSWORD=couchdb. This is the default value when bootstrapping CouchDB and should not be used in production environments.
couchdb 12:07:54.63 INFO  ==> Initializing CouchDB...
couchdb 12:07:54.63 INFO  ==> Updating '/opt/bitnami/couchdb/etc/default.d/10-bitnami.ini' based on user configuration...
couchdb 12:07:54.66 INFO  ==> Updating '/opt/bitnami/couchdb/etc/vm.args' based on user configuration...
couchdb 12:07:54.66 INFO  ==> Deploying CouchDB from scratch
couchdb 12:07:54.66 INFO  ==> Starting CouchDB in background...
couchdb 12:07:55.67 INFO  ==> Creating initial databases...
couchdb 12:07:55.78 INFO  ==> Stopping CouchDB...

couchdb 12:07:57.29 INFO  ==> ** CouchDB setup finished! **
couchdb 12:07:57.29 INFO  ==> ** Starting CouchDB **
[info] 2020-06-24T12:07:57.874602Z couchdb@127.0.0.1 <0.240.0> -------- Preflight check: Asserting Admin Account

[info] 2020-06-24T12:07:57.876339Z couchdb@127.0.0.1 <0.240.0> -------- Apache CouchDB 3.1.0 is starting.

[info] 2020-06-24T12:07:57.876412Z couchdb@127.0.0.1 <0.241.0> -------- Starting couch_sup
[info] 2020-06-24T12:07:57.913370Z couchdb@127.0.0.1 <0.240.0> -------- Apache CouchDB has started. Time to relax.

[notice] 2020-06-24T12:07:57.919219Z couchdb@127.0.0.1 <0.273.0> -------- rexi_server : started servers
[notice] 2020-06-24T12:07:57.920205Z couchdb@127.0.0.1 <0.277.0> -------- rexi_buffer : started servers
[notice] 2020-06-24T12:07:57.955896Z couchdb@127.0.0.1 <0.307.0> -------- mem3_reshard_dbdoc start init()
[notice] 2020-06-24T12:07:57.958362Z couchdb@127.0.0.1 <0.309.0> -------- mem3_reshard start init()
[notice] 2020-06-24T12:07:57.958441Z couchdb@127.0.0.1 <0.310.0> -------- mem3_reshard db monitor <0.310.0> starting
[notice] 2020-06-24T12:07:57.959715Z couchdb@127.0.0.1 <0.309.0> -------- mem3_reshard starting reloading jobs
[notice] 2020-06-24T12:07:57.959825Z couchdb@127.0.0.1 <0.309.0> -------- mem3_reshard finished reloading jobs
[notice] 2020-06-24T12:08:02.983221Z couchdb@127.0.0.1 <0.361.0> -------- couch_replicator_clustering : cluster stable
[notice] 2020-06-24T12:08:02.985338Z couchdb@127.0.0.1 <0.380.0> -------- Started replicator db changes listener <0.501.0>
[info] 2020-06-24T12:08:02.985671Z couchdb@127.0.0.1 <0.503.0> -------- open_result error {not_found,no_db_file} for _replicator
[notice] 2020-06-24T12:08:03.028074Z couchdb@127.0.0.1 <0.501.0> -------- creating replicator ddoc <<"shards/80000000-ffffffff/_replicator.1593000475">>
[notice] 2020-06-24T12:08:12.920204Z couchdb@127.0.0.1 <0.273.0> -------- rexi_server : cluster stable
[notice] 2020-06-24T12:08:12.920260Z couchdb@127.0.0.1 <0.277.0> -------- rexi_buffer : cluster stable
```

**Closed by carrodher** 2020-06-24 12:09 UTC

**Comment by thomascenni** [comment] 2020-06-24 12:52
> docker-compose.yaml

Thanks for the answer, it is working.
But to be able to login to the server, may be it is also needed a COUCHDB_ADMIN_USERNAME ?

**Comment by carrodher** [comment] 2020-06-24 18:24
Yes, you can see the different configuration options in this section of the README: https://github.com/bitnami/bitnami-docker-couchdb#configuration
